spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.10.10:3306/uhome
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

spring.devtools.restart.enabled: true
spring.devtools.restart.additional-paths: src/main/java


